[package]
name = "amethyst_pong"
version = "0.2.0"
authors = ["Fluhzar <fluhzar@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.amethyst]
version = "0.15"
features = ["vulkan"]
